set_attribute [get_lib_cells */b15qgbbf*] dont_use true
set_attribute [get_lib_cells */b15qgbao*] dont_use true
set_attribute [get_lib_cells */b15qgbbd*] dont_use true
set_attribute [get_lib_cells */b15qgbbf*] dont_use true
set_attribute [get_lib_cells */b15qgbff*] dont_use true
set_attribute [get_lib_cells */b15qgbin*] dont_use true
set_attribute [get_lib_cells */b15qgblf*] dont_use true
set_attribute [get_lib_cells */b15qgbmx*] dont_use true
set_attribute [get_lib_cells */b15qgbna*] dont_use true
set_attribute [get_lib_cells */b15qgbno*] dont_use true
set_attribute [get_lib_cells */b15qgboa*] dont_use true
set_attribute [get_lib_cells */b15qgbxo*] dont_use true
set_attribute [get_lib_cells */b15qgbdc*] dont_use true
set_attribute [get_lib_cells */b15qgbdp*] dont_use true
set_attribute [get_lib_cells */b15qgbth*] dont_use true
set_attribute [get_lib_cells */b15qgbtl*] dont_use true
set_attribute [get_lib_cells */b15cbf*] dont_use true
set_attribute [get_lib_cells */b15cdiyr*] dont_use true
set_attribute [get_lib_cells */b15cinv*] dont_use true
set_attribute [get_lib_cells */b15clb*] dont_use true
set_attribute [get_lib_cells */b15cmbn*] dont_use true
set_attribute [get_lib_cells */b15cpsan*] dont_use true
set_attribute [get_lib_cells */b15cpsbf*] dont_use true
set_attribute [get_lib_cells */b15cpsin*] dont_use true
set_attribute [get_lib_cells */b15cpsor*] dont_use true
set_attribute [get_lib_cells */b15fmy20*] dont_use true
set_attribute [get_lib_cells */b15fmy30*] dont_use true
set_attribute [get_lib_cells */b15bfm*] dont_use true
